Unit 9
Pavlobuch/autoTests pull request #1
Opened 2023-12-01 19:50 UTC by Pavlobuch

2023-12-02 07:39 UTC, ovartem requested changes
Well done!
The tests itself looks great!

But

Every JS repo should contain some additional files:
- package.json
- package-lock.json
and in your case - playwright.config.js

Without those files I won't be able to clone it and run your tests

2023-12-02 07:39 UTC, ovartem commented on tests/mytests.spec.js
> +async function login (page) {
Well done!
There is a mechanism so called hooks - which can be used to do necessary preconditions before each test - [beforeEach](https://playwright.dev/docs/api/class-test#test-before-each-1). check out - there some others as well

2023-12-02 07:39 UTC, ovartem commented on tests/mytests.spec.js
> +    expect(numberOfProducts).toBeGreaterThan(1)
Great!

2023-12-03 12:43 UTC, ovartem requested changes
Small change is still needed

2023-12-03 12:43 UTC, ovartem commented on playwright.config.js
> +    // baseURL: 'http://127.0.0.1:3000',
You can add url to visit here and don't add it in every test

2023-12-03 20:40 UTC, hlazkov approved these changes
Looks nice!

2023-12-05 19:50 UTC, merged